# Generated by Django 3.2.7 on 2021-10-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='onetofive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('class2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('class3', models.DecimalField(decimal_places=2, max_digits=3)),
                ('class4', models.DecimalField(decimal_places=2, max_digits=3)),
                ('class5', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
