# Generated by Django 3.2.7 on 2021-10-04 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_auto_20211004_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class6', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class7', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class8', models.DecimalField(decimal_places=2, max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='onetofive',
        ),
    ]
