# Generated by Django 3.2.7 on 2021-10-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20211004_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_strength5',
            name='owner',
        ),
    ]
