# Generated by Django 3.2.5 on 2021-10-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumption',
        ),
    ]
